
pipeline {
    agent any
    environment {
        REPO = "s10-webmobile1-sub2/S10P12C110"
        DOCKERHUB_REGISTRY = "pji0128/front"
        DOCKERHUB_CREDENTIALS = credentials('Docker-credential')

    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage("Build") {
            steps {
                script {
                    sh "ls -al"

                    sh "docker build -t ${DOCKERHUB_REGISTRY} FrontEnd"
                }
            }
        }

        stage("Login") {
            steps {
                sh "echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u \${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                
            }
        }
        stage("Tag and Push") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD')]) {
                        sh "docker push ${DOCKERHUB_REGISTRY}"
                    }
                }
            }
        }

        stage('Prune old images') {
            steps {
                script {
                    sh "docker ps"
                    // sh "docker system prune --filter until=1h"
                }
            }
        }
        stage('Pull') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD')]) {
                        sh "docker stop front || true"
                        sh "docker rm front || true"
                        sh "docker rmi ${DOCKERHUB_REGISTRY}|| true"     //images 날리기
                        sh "docker pull ${DOCKERHUB_REGISTRY}"

                                               
                    }
                }
            }
        }

        stage('Up') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'Docker-hub', usernameVariable: 'DOCKER_USER_ID', passwordVariable: 'DOCKER_USER_PASSWORD')]) {
                        try{
                            sh "docker run -d --name front -p 8083:4173 \
                            ${DOCKERHUB_REGISTRY}"
                        } catch (Exception e){
                            sh "docker restart front || true"
                        }
                    }
                }
            }
        }
    }
}
